resolver: lts-12.12
packages:
- '.'

extra-deps:
- thyme-0.3.5.5
- Chart-1.9
- Chart-cairo-1.9


flags: {}

extra-package-dbs: []
nix:
  packages: [pkgconfig, cairo, zlib, pango, xorg.xproto, xorg.libX11, gtk2, gtk3]
